In [1]:
from keras.applications.resnet import ResNet50, preprocess_input
from keras.models import Model, load_model
from keras.preprocessing import image
from keras.utils import load_img, img_to_array
import numpy as np
import matplotlib.image as mpimg
import matplotlib.pyplot as plt
import os, shutil, pathlib

2023-04-05 13:05:08.716454: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
model = ResNet50(weights="imagenet", input_shape=(224, 224, 3))
model.summary()

Model: "resnet50"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_1 (InputLayer)           [(None, 224, 224, 3  0           []                               
                                )]                                                                
                                                                                                  
 conv1_pad (ZeroPadding2D)      (None, 230, 230, 3)  0           ['input_1[0][0]']                
                                                                                                  
 conv1_conv (Conv2D)            (None, 112, 112, 64  9472        ['conv1_pad[0][0]']              
                                )                                                                 
                                                                                           

In [3]:
model_n = Model(model.input, model.layers[-2].output)

In [4]:
def preprocess_img(img):
    img = load_img(img, target_size=(224, 224,))
    img = img_to_array(img)
    img = np.expand_dims(img, axis=0)
    img = preprocess_input(img)
    return img

In [5]:
def encode_img(img):
    img = preprocess_img(img)
    feature_v = model_n.predict(img)
    feature_v = feature_v.reshape((-1,))
    return feature_v

In [6]:
breed_list = os.listdir('data/train/')
breed_list.remove('.DS_Store')
print(breed_list)

['Yorkie', 'Greyhound', 'Corgi', 'Mex Hairless', 'Boston Terrier', 'Blenheim', 'Scotch Terrier', 'Rottweiler', 'Elk Hound', 'Schnauzer', 'Bull Mastiff', 'Pomeranian', 'Pekinese', 'Pit Bull', 'Basenji', 'French Bulldog', 'Coyote', 'Komondor', 'Great Perenees', 'Basset', 'Great Dane', 'Dhole', 'Lhasa', 'Labrador', 'Chinese Crested', 'Cocker', 'Chihuahua', 'Shiba Inu', 'Newfoundland', 'Dalmation', 'Bull Terrier', 'Pug', 'Afghan', 'Cairn', 'Beagle', 'Cockapoo', 'Vizsla', 'Collie', 'Irish Wolfhound', 'American Spaniel', 'Maltese', 'African Wild Dog', 'Doberman', 'Shih-Tzu', 'German Sheperd', 'Labradoodle', 'Groenendael', 'Border Collie', 'Shar_Pei', 'Bearded Collie', 'Bermaise', 'Saint Bernard', 'Rhodesian', 'Siberian Husky', 'Japanese Spaniel', 'Borzoi', 'Chow', 'Airedale', 'Dingo', 'American Hairless', 'Irish Spaniel', 'Poodle', 'Malinois', 'Bichon Frise', 'Golden Retriever', 'Clumber', 'Boxer', 'Bulldog', 'Bloodhound', 'Bluetick']


In [7]:
os.mkdir('breed')
os.mkdir('breed/train')
os.mkdir('breed/valid')
os.mkdir('breed/test')
for i in breed_list:
    os.mkdir(f'breed/train/{i}')
    os.mkdir(f'breed/valid/{i}')
    os.mkdir(f'breed/test/{i}')

In [8]:
var1 = []
for breed in breed_list:
    var1.append(len(os.listdir('data/train/'+f'{breed}')))
print(min(var1))

65


In [9]:
# select first 64 photos of each class

In [10]:
for i in breed_list:
    source = 'data/train/'+f'{i}'
    for j in os.listdir(source)[:64]:
        shutil.copy(src=source+'/'+f'{j}', dst='breed/train/'+f'{i}')

In [11]:
for i in breed_list:
    source = 'data/valid/'+f'{i}'
    for j in os.listdir(source)[:8]:
        shutil.copy(src=source+'/'+f'{j}', dst='breed/valid/'+f'{i}')

In [12]:
for i in breed_list:
    source = 'data/test/'+f'{i}'
    for j in os.listdir(source)[:8]:
        shutil.copy(src=source+'/'+f'{j}', dst='breed/test/'+f'{i}')

In [13]:
feature = {}
for i in breed_list:
    feature[f'{i}'] = []

In [14]:
print(feature)

{'Yorkie': [], 'Greyhound': [], 'Corgi': [], 'Mex Hairless': [], 'Boston Terrier': [], 'Blenheim': [], 'Scotch Terrier': [], 'Rottweiler': [], 'Elk Hound': [], 'Schnauzer': [], 'Bull Mastiff': [], 'Pomeranian': [], 'Pekinese': [], 'Pit Bull': [], 'Basenji': [], 'French Bulldog': [], 'Coyote': [], 'Komondor': [], 'Great Perenees': [], 'Basset': [], 'Great Dane': [], 'Dhole': [], 'Lhasa': [], 'Labrador': [], 'Chinese Crested': [], 'Cocker': [], 'Chihuahua': [], 'Shiba Inu': [], 'Newfoundland': [], 'Dalmation': [], 'Bull Terrier': [], 'Pug': [], 'Afghan': [], 'Cairn': [], 'Beagle': [], 'Cockapoo': [], 'Vizsla': [], 'Collie': [], 'Irish Wolfhound': [], 'American Spaniel': [], 'Maltese': [], 'African Wild Dog': [], 'Doberman': [], 'Shih-Tzu': [], 'German Sheperd': [], 'Labradoodle': [], 'Groenendael': [], 'Border Collie': [], 'Shar_Pei': [], 'Bearded Collie': [], 'Bermaise': [], 'Saint Bernard': [], 'Rhodesian': [], 'Siberian Husky': [], 'Japanese Spaniel': [], 'Borzoi': [], 'Chow': [], 'Ai

In [16]:
for i in breed_list:
    temp_path = 'breed/train/'+f'{i}'
    print(temp_path)
    print(os.listdir(temp_path))
    for j in os.listdir(temp_path):
        feature_vector = encode_img(temp_path+'/'+f'{j}')
        feature[f'{i}'].append(feature_vector)

breed/train/Yorkie
['63.jpg', '77.jpg', '76.jpg', '62.jpg', '74.jpg', '60.jpg', '48.jpg', '49.jpg', '61.jpg', '75.jpg', '59.jpg', '71.jpg', '65.jpg', '64.jpg', '70.jpg', '58.jpg', '66.jpg', '72.jpg', '73.jpg', '67.jpg', '14.jpg', '28.jpg', '29.jpg', '15.jpg', '01.jpg', '17.jpg', '03.jpg', '02.jpg', '16.jpg', '12.jpg', '06.jpg', '07.jpg', '13.jpg', '39.jpg', '05.jpg', '11.jpg', '10.jpg', '04.jpg', '38.jpg', '21.jpg', '35.jpg', '09.jpg', '08.jpg', '34.jpg', '20.jpg', '36.jpg', '22.jpg', '23.jpg', '37.jpg', '33.jpg', '27.jpg', '26.jpg', '32.jpg', '18.jpg', '24.jpg', '30.jpg', '31.jpg', '25.jpg', '19.jpg', '42.jpg', '56.jpg', '57.jpg', '43.jpg', '55.jpg']
1/1 [==============================] - 0s 115ms/step
breed/train/Greyhound
['016.jpg', '002.jpg', '003.jpg', '017.jpg', '029.jpg', '001.jpg', '015.jpg', '014.jpg', '028.jpg', '004.jpg', '010.jpg', '038.jpg', '039.jpg', '011.jpg', '005.jpg', '013.jpg', '007.jpg', '006.jpg', '012.jpg', '101.jpg', '049.jpg', '075.jpg', '061.jpg', '060.jpg', 

In [17]:
from sklearn.metrics.pairwise import cosine_similarity

In [18]:
feature['Yorkie'][0]

array([0.        , 0.7193324 , 0.05600223, ..., 1.1271602 , 0.1440109 ,
       0.62488645], dtype=float32)

In [19]:
feature['Yorkie'][1]

array([0.11862457, 0.6782994 , 0.06082774, ..., 0.12787008, 0.2582552 ,
       0.7238894 ], dtype=float32)

In [20]:
print(breed_list)

['Yorkie', 'Greyhound', 'Corgi', 'Mex Hairless', 'Boston Terrier', 'Blenheim', 'Scotch Terrier', 'Rottweiler', 'Elk Hound', 'Schnauzer', 'Bull Mastiff', 'Pomeranian', 'Pekinese', 'Pit Bull', 'Basenji', 'French Bulldog', 'Coyote', 'Komondor', 'Great Perenees', 'Basset', 'Great Dane', 'Dhole', 'Lhasa', 'Labrador', 'Chinese Crested', 'Cocker', 'Chihuahua', 'Shiba Inu', 'Newfoundland', 'Dalmation', 'Bull Terrier', 'Pug', 'Afghan', 'Cairn', 'Beagle', 'Cockapoo', 'Vizsla', 'Collie', 'Irish Wolfhound', 'American Spaniel', 'Maltese', 'African Wild Dog', 'Doberman', 'Shih-Tzu', 'German Sheperd', 'Labradoodle', 'Groenendael', 'Border Collie', 'Shar_Pei', 'Bearded Collie', 'Bermaise', 'Saint Bernard', 'Rhodesian', 'Siberian Husky', 'Japanese Spaniel', 'Borzoi', 'Chow', 'Airedale', 'Dingo', 'American Hairless', 'Irish Spaniel', 'Poodle', 'Malinois', 'Bichon Frise', 'Golden Retriever', 'Clumber', 'Boxer', 'Bulldog', 'Bloodhound', 'Bluetick']


In [21]:
test_gold = encode_img('breed/valid/Golden Retriever/03.jpg')

1/1 [==============================] - 0s 126ms/step


In [29]:
test_lau = encode_img('Lau.jpeg')

1/1 [==============================] - 0s 238ms/step


In [22]:
cosine_similarity(test_gold.reshape(1,-1), feature['Yorkie'][0].reshape(1,-1))

array([[0.3778239]], dtype=float32)

In [114]:
def check_image_ver0(testing):
    check = encode_img(testing)
    name = []
    for i in breed_list:
        temp_list = feature[f'{i}']
        temp1 = []
        for j in temp_list:
            score = cosine_similarity(check.reshape(1,-1), j.reshape(1,-1))[0][0]
            if score > 0.60:
                temp1.append(score)
                if len(temp1) > 40:
                    name.append(i)

    if len(list(dict.fromkeys(name)))==1:
        for k in list(dict.fromkeys(name)):
            print("This is a", k)
    elif len(list(dict.fromkeys(name)))>1:
        print("There are more than one possible outcomes!")
        for k in list(dict.fromkeys(name)):
            print("This may be a", k)
    elif len(list(dict.fromkeys(name)))==0:
        print("No such class! Your image may not be a dog")

In [129]:
def check_image(testing):
    check = encode_img(testing)
    name = []
    for i in breed_list:
        temp_list = feature[f'{i}']
        temp1 = []
        for j in temp_list:
            score = cosine_similarity(check.reshape(1,-1), j.reshape(1,-1))[0][0]
            if score > 0.50:
                temp1.append(score)
                if len(temp1) > 50:
                    name.append(i)
    name_list = list(dict.fromkeys(name))
    if len(name_list)==1:
        for k in name_list:
            print("This is a", k)
    elif len(name_list)>1:
        temp2 = []
        for l in name_list:
            temp3 = []
            temp_list2 = feature[f'{l}']
            for m in temp_list2:
                score = cosine_similarity(check.reshape(1,-1), m.reshape(1,-1))[0][0]
                temp3.append(score)
            temp2.append(sum(temp3))
        print("This is a", name_list[np.argmax(temp2)])
    elif len(name_list)==0:
        print("No such class! Your image may not be a dog")

In [110]:
sum([1, 2, 3, 4])

10

In [138]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image_ver0(f'breed/valid/Bloodhound/0{name}.jpg')

1/1 [==============================] - 0s 134ms/step
This is a Bloodhound
1/1 [==============================] - 0s 152ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 112ms/step
There are more than one possible outcomes!
This may be a Basset
This may be a Bloodhound
1/1 [==============================] - 0s 110ms/step
This is a Bloodhound
1/1 [==============================] - 0s 114ms/step
There are more than one possible outcomes!
This may be a Basset
This may be a Bloodhound
1/1 [==============================] - 0s 116ms/step
This is a Bloodhound
1/1 [==============================] - 0s 114ms/step
This is a Bloodhound


In [139]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image(f'breed/valid/Bloodhound/0{name}.jpg')

1/1 [==============================] - 0s 149ms/step
This is a Bloodhound
1/1 [==============================] - 0s 111ms/step
This is a Bloodhound
1/1 [==============================] - 0s 118ms/step
This is a Bloodhound
1/1 [==============================] - 0s 157ms/step
This is a Bloodhound
1/1 [==============================] - 0s 113ms/step
This is a Bloodhound
1/1 [==============================] - 0s 118ms/step
This is a Bloodhound
1/1 [==============================] - 0s 113ms/step
This is a Bloodhound


In [140]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image_ver0(f'breed/valid/German Sheperd/0{name}.jpg')

1/1 [==============================] - 0s 221ms/step
This is a German Sheperd
1/1 [==============================] - 0s 115ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 110ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 109ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 114ms/step
There are more than one possible outcomes!
This may be a German Sheperd
This may be a Groenendael
1/1 [==============================] - 0s 120ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 112ms/step
This is a German Sheperd


In [141]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image(f'breed/valid/German Sheperd/0{name}.jpg')

1/1 [==============================] - 0s 122ms/step
This is a German Sheperd
1/1 [==============================] - 0s 109ms/step
This is a German Sheperd
1/1 [==============================] - 0s 113ms/step
This is a German Sheperd
1/1 [==============================] - 0s 124ms/step
This is a German Sheperd
1/1 [==============================] - 0s 111ms/step
This is a German Sheperd
1/1 [==============================] - 0s 204ms/step
This is a Groenendael
1/1 [==============================] - 0s 202ms/step
This is a German Sheperd


In [142]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image_ver0(f'breed/valid/French Bulldog/0{name}.jpg')

1/1 [==============================] - 0s 118ms/step
This is a French Bulldog
1/1 [==============================] - 0s 113ms/step
There are more than one possible outcomes!
This may be a Boston Terrier
This may be a French Bulldog
1/1 [==============================] - 0s 119ms/step
No such class! Your image may not be a dog
1/1 [==============================] - 0s 130ms/step
There are more than one possible outcomes!
This may be a Boston Terrier
This may be a French Bulldog
1/1 [==============================] - 0s 149ms/step
This is a French Bulldog
1/1 [==============================] - 0s 224ms/step
There are more than one possible outcomes!
This may be a Boston Terrier
This may be a French Bulldog
1/1 [==============================] - 0s 111ms/step
There are more than one possible outcomes!
This may be a Boston Terrier
This may be a French Bulldog


In [143]:
for name in [1, 2, 3, 4, 5, 6, 7]:
    check_image(f'breed/valid/French Bulldog/0{name}.jpg')

1/1 [==============================] - 0s 119ms/step
This is a French Bulldog
1/1 [==============================] - 0s 113ms/step
This is a French Bulldog
1/1 [==============================] - 0s 112ms/step
This is a French Bulldog
1/1 [==============================] - 0s 187ms/step
This is a French Bulldog
1/1 [==============================] - 0s 112ms/step
This is a French Bulldog
1/1 [==============================] - 0s 110ms/step
This is a French Bulldog
1/1 [==============================] - 0s 109ms/step
This is a French Bulldog


In [144]:
check_image('Lau.jpeg')

1/1 [==============================] - 0s 115ms/step
No such class! Your image may not be a dog
